# Generated by Django 5.2.7 on 2025-10-24 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('CLIENT_NUMBER', models.IntegerField(db_column='CLIENT_NUMBER', primary_key=True, serialize=False, verbose_name='Client Number')),
                ('CLIENT_LNAME', models.CharField(blank=True, db_column='CLIENT_LNAME', max_length=40, null=True, verbose_name='Last Name')),
                ('CLIENT_FNAME', models.CharField(blank=True, db_column='CLIENT_FNAME', max_length=20, null=True, verbose_name='First Name')),
                ('CLIENT_STATUS', models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive'), ('B', 'Blocked'), ('S', 'Special'), ('R', 'Blocked by Resignation')], db_column='CLIENT_STATUS', max_length=1, null=True, verbose_name='Client Status')),
                ('CLIENT_DMYADM', models.DateField(blank=True, db_column='CLIENT_DMYADM', null=True, verbose_name='Date of Admission')),
                ('CLIENT_ID', models.CharField(db_column='CLIENT_ID', max_length=15, verbose_name='Client ID')),
                ('CLIENT_DMYBIR', models.DateField(blank=True, db_column='CLIENT_DMYBIR', null=True, verbose_name='Date of Birth')),
                ('CLIENT_SEX', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], db_column='CLIENT_SEX', max_length=1, null=True, verbose_name='Client Sex')),
                ('CLIENT_ADDRESS', models.CharField(blank=True, db_column='CLIENT_ADDRESS', max_length=120, null=True, verbose_name='Client Address')),
                ('CLIENT_PHONE', models.CharField(blank=True, db_column='CLIENT_PHONE', max_length=15, null=True, verbose_name='Client Phone')),
                ('CLIENT_CITY', models.CharField(blank=True, db_column='CLIENT_CITY', max_length=30, null=True, verbose_name='Client City')),
                ('CLIENT_IDORIGIN', models.CharField(blank=True, db_column='CLIENT_IDORIGIN', max_length=30, null=True, verbose_name='ID Client Origin')),
            ],
            options={
                'verbose_name': 'client',
                'db_table': 'client',
                'ordering': ['CLIENT_NUMBER'],
            },
        ),
        migrations.CreateModel(
            name='cligeopos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIGEO_TYPPOS', models.CharField(blank=True, choices=[('D', 'home/dwelling'), ('J', 'Job/ bussiness')], db_column='CLIGEO_TYPPOS', max_length=50, null=True, verbose_name='Position Type')),
                ('CLIGEO_LATITUDE', models.CharField(blank=True, db_column='CLIGEO_LATITUDE', max_length=150, null=True, verbose_name='Latitude')),
                ('CLIGEO_LENGHT', models.CharField(blank=True, db_column='CLIGEO_LENGHT', max_length=120, null=True, verbose_name='Length')),
                ('CLIGEO_OBSER', models.TextField(blank=True, db_column='CLIGEO_OBSER', null=True, verbose_name='Observation')),
                ('CLIGEO_NUMBER', models.ForeignKey(blank=True, db_column='CLIGEO_NUMBER', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CLIGEO_NUMBER', to='core.client', verbose_name='Client Number')),
            ],
        ),
    ]
